config/routes.rb
Rails.application.routes.draw do
  resources :books
  root :to => redirect('/books')

  get '/books/:id/similar_books' => 'books#search_similar_books', as: :search_similar_books
end

app/models/book.rb
class Book < ActiveRecord::Base
    def self.all_genres ; ['Science fiction', 'Drama', 'Action and Adventure', 'Romance', 'Mystery', 'Horror'] end
    def self.similar_books(book)
      Book.where author: book.author
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    sort = params[:sort] || session[:sort]

    case sort
      when 'title'
      ordering,@title_header = {:title => :asc}, 'hilite'
      when 'publish_date'      
      ordering,@date_header = {:publish_date => :asc}, 'hilite'
    end
    
    @all_genres = Book.all_genres  
    @selected_genres = params[:genres] || session[:genres] || {}
    
    if @selected_genres == {}   
      @selected_genres = Hash[@all_genres.map {|genre| [genre, genre]}]
    end

    if params[:sort] != session[:sort] or params[:genres] != session[:genres]
      session[:sort] = sort
      session[:genres] = @selected_genres
      redirect_to :sort => sort, :genres => @selected_genres and return
    end
    
    @books = Book.where(genre: @selected_genres.keys).order(ordering)
  end
  
  def show
    id = params[:id] # retrieve book ID from URI route
    @book = Book.find(id) # look up book by unique ID
  end
  
  def create
    params.require(:book)
    permitted = params[:book].permit(:title,:genre, :isbn_number, :publish_date, :description, :author)
    @book = Book.create!(permitted)
    flash[:notice] = "#{@book.title} was successfully created."
    redirect_to books_path
  end
  
  def edit
    @book = Book.find params[:id]
  end

  def update
    @book = Book.find params[:id]
    params.require(:book)
    permitted = params[:book].permit(:title,:genre, :isbn_number, :publish_date, :description, :author)
    @book.update_attributes!(permitted)
    flash[:notice] = "#{@book.title} was successfully updated."
    redirect_to book_path(@book)
  end
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = "Book '#{@book.title}' deleted."
    redirect_to books_path
  end
  
  def search_similar_books
    @book = Book.find(params[:id])
    if @book.author.nil? || @book.author.empty?
      flash[:warning]= "'#{@book.title}' has no author info"
      redirect_to books_path
    else
      @books = Book.similar_books(@book)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/edit.html.haml
%h2 Edit Book

= form_tag book_path(@book), :method => :put do

  = label :book, :title, 'Title'
  = text_field :book, :title

  = label :book, :genre, 'Genre'
  = select :book, :genre, ['Science fiction','Drama','Action and Adventure','Romance','Mystery', 'Horror']
 
  = label :book, :description, 'Description'
  = text_field :book, :description
  
  = label :book, :isbn_number, 'ISBN Number'
  = text_field :book, :isbn_number
 
  = label :book, :publish_date, 'Published On'
  = date_select :book, :publish_date
  
  = label :book, :author, 'Author'
  = text_field :book, 'author'

  = submit_tag 'Update Book Info'

app/views/books/index.html.haml
%h1 All Books
= form_tag books_path, :method => :get, :id => 'books_form' do
  = hidden_field_tag "title_sort", true if @title_header
  = hidden_field_tag ":publish_date_sort", true if @date_header

  Include:
  - @all_genres.each do |genre|
    = genre
    = check_box_tag "genres[#{genre}]", 1, @selected_genres.include?(genre), :id => "genres_#{genre}"
  = submit_tag 'Refresh', :id => 'genres_submit'
%table#books
  %thead
    %tr
      %th{:class => @title_header}= link_to 'Book Title', books_path(:sort => 'title'), :id => 'title_header'
      %th Genre
      %th ISBN Number
      %th{:class => @date_header}= link_to 'Publish Date', books_path(:sort => 'publish_date'), :id => 'publish_date_header'
      %th More Info
  %tbody
    - @books.each do |book|
      %tr
        %td= book.title
        %td= book.genre
        %td= book.isbn_number
        %td= book.publish_date.strftime("%B %d, %Y")
        %td= link_to "More about #{book.title}", book_path(book)
        
= link_to 'Add new book', new_book_path

app/views/books/new.html.haml
%h2 Create New Book

= form_tag books_path, :method => :post do

  = label :book, :title, 'Title'
  = text_field :book, :title

  = label :book, :genre, 'Genre'
  = select :book, :genre, ['Science fiction','Drama','Action and Adventure','Romance','Mystery', 'Horror']
 
  = label :book, :description, 'Description'
  = text_field :book, :description
  
  = label :book, :isbn_number, 'ISBN Number'
  = text_field :book, :isbn_number
 
  = label :book, :publish_date, 'Published On'
  = date_select :book, :publish_date

  = submit_tag 'Save Changes'

app/views/books/search_similar_books.html.haml
%h1 Books with same author #{@book.title}

%table#similar_books
  %thead
    %tr
      %th Book Title
      %th Genre
      %th ISBN number
      %th Publish Date
      %th Author
      %th More Info
  %tbody
    - @books.each do |book|
      %tr
        %td= book.title 
        %td= book.genre
        %td= book.isbn_number
        %td= book.publish_date
        %td= book.author
        %td= link_to "More about #{book.title}", book_path(book)

app/views/books/show.html.haml
%h2 Details about #{@book.title}

%ul#details
  %li
    Title:
    = @book.title
  %li
    Genre:
    = @book.genre
  %li
    ISBN Number:
    = @book.isbn_number
  %li
    Publish Date:
    = @book.publish_date.strftime("%B %d, %Y")
  %li
    Description:
    = @book.description

  = link_to 'Edit book', edit_book_path(@book)
  = link_to 'Delete book', book_path(@book), :method => :delete
  = link_to 'Find Books With Same Author', search_similar_books_url(id: @book.id)
  = link_to 'Go back to listing', books_path

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title MyFavoriteBooks!
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    - if flash[:notice]
      #notice.message= flash[:notice]
    - elsif flash[:warning]
      #warning.message= flash[:warning]
    #main
      = yield